### ISSUE TITLE
Create a client app which draws triangles from binary STL file.

### ISSUE THREAD

**Issue by Aki-7** [gray-armor/z11#23]
STLファイルをメッシュで描画するのはもうできそう。
四角形だけではつまらないので、作りたい。

STLファイルの仕様: https://ja.wikipedia.org/wiki/Standard_Triangulated_Language
Binary STLサンプル: https://www.applicraft.com/d3c/

**Comment by shierote** [comment]
でかい建物とかも描画したいなー
想定のデモにぐっと近づけるね
https://github.com/stephenyeargin/stl-files

**Comment by Aki-7** [comment]
これ江口やりたい？

**Comment by shierote** [comment]
おれやるよー
