### ISSUE TITLE
Implement frame callback

### ISSUE THREAD

**Issue by Aki-7** [gray-armor/z11#30]
WaylandではCompositorが知っている(Compositorしか知らない)ディスプレイのリフレッシュレートをclientに伝える手段がある。

clientはwl_surfaceをcommitする(つまり新しい描画情報があって、準備できていることをCompositorに伝える) 前にframeというrequestを送る(also see [interface detail](https://github.com/gray-armor/wiki/wiki/wl_surface-Wayland-Interface))。これはcallbackを引数にしていて、compositorはこのcallbackを叩くことでクライアントに次のcommitをして良いことを伝える。compositorは自身が知っているディスプレイのリフレッシュレートに合わせてこのcallbackを呼ぶタイミングを調整することでクライアントもリフレッシュレートに合わせてcommitをすることができ、無駄な描画をせずに済む。

この機構をZにも入れたい。というか入れないとZWaylandを作り始められない。

現状の実装ではmain loopが `-no-hmd` で60hz, hmdありだと45hzだと聞いた。
どこかでブロッキングが発生していてもったいない。
これは`-no-hmd`の場合はSDLがリフレッシュレートに合わせてOpenGLのバッファから読み出しているせいだが、[SDL_GL_SetSwapInterval](https://wiki.libsdl.org/SDL_GL_SetSwapInterval)に0を設定すれば1000hzくらい出ることを確認している。hmdありの場合は`Hmd::UpdateHeadPose()`の`vr::VRCompositor()->WaitGetPoses()`あたりがblockしてそう。[このコメント](https://github.com/ValveSoftware/openvr/issues/434#issuecomment-292254972)あたりの情報を使うとno-blockingにPoseを取得できそう。@shierote 確認してみて欲しい。

これを成し遂げて、むだなblockingを排除した上でHMDのフレッシュレートに合わせて描画できるようにしたい。
HTC VIVE のリフレッシュレートは90Hzだとおもうので。

接続されているデバイスのリフレッシュレートはどう取得するのかだけど、ぱっとみOpenVRからは取得できない？vsyncのような機構はない？っぽいし、144Hz出るからといって、144Hz出す必要が常にあるとは限らないし、今後ユーザがリフレッシュレートは変更できるようにするとして、とりま90Hzに固定とかでもいいのかもしれない。

main loopで90秒に一回OpenGLのrenderingとHMD, SDLへのswapを行い。その直前か直後にframeのcallbackを呼ぶのが良いと思われる。そのcallbackによってクライアントが次に行うcommitの内容は次のswap時に描画される内容になる。のでlatencyが最大1/90 secできるけど。ここの最適化は今は考えない。

**Comment by shierote** [comment]
HMDの場合も `SDL_GL_SetSwapInterval` を0にすれば、82~89Hzくらいは出てる。

**Comment by shierote** [comment]
OpenVRのコメントで紹介されていた `vr::VRCompositor()->GetLastPoses();` を使うと、3000fpsくらい出るが、HMDには何も描画されない（SDLには描画される。）この原因はなぜかわかっていない。
