### ISSUE TITLE
Complete ray creation

### ISSUE THREAD

**Issue by Aki-7** [gray-armor/z11#63]
ray / ray client のclientとのやりとりの部分の未実装の部分
- 一つのclientが複数回 get_ray した場合(プロトコルエラーにはしない。全てに同じeventを送る。)
- ray と ray client を紐づける
などを実装する。

**Comment by shierote** [comment]
westonだと rayのメンバにfocus_client (or focus_client_list) があってそこにfocus中ののclientを入れてるっぽい

**Comment by Aki-7** [comment]
> ray と ray client を紐づける 

こっちの方のはなしだよね、

> westonだと ~ray~ pointerのメンバにfocus_client (or focus_client_list) があってそこにfocus中ののclientを入れてるっぽい

それはfocusがあったてるpointerへの参照だよね？基本的には pointer->pointer_clientsじゃない？
